version: '2'
services:
  drive-nginx:
    image: nginx:alpine
    container_name: dirve-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - drive-react
  drive-react:
    container_name: drive-react
    hostname: drive-react
    ports:
      - "3000:3000"
      - "35729:35729"
    image: node:9.5
    command: [sh, -c, yarn && yarn start]
    volumes:
      - ./react/.:/app
    working_dir: /app
